name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: windows-2022
    steps:
      - name: "API Tests"
        uses: cypress-io/github-action@v6
        with:
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          spec: cypress/tests/e2e/api/*
          config-file: cypress.config.ts
